---
- hosts: meta-infra_type_gerrit
  user: ubuntu
  gather_facts: no
  sudo: true
  tasks:
  name: Run Puppet to install Gerrit
  tasks:
    - puppet:
      ignore_errors: yes
    - service: name=apache2 state=started
