---
# file: site.yml
- include: common.yml
- include: set_hostnames.yml
- include: bootstrap_puppetmaster.yml
- include: bootstrap_gerrit.yml
- include: bootstrap_puppet_infra_nodes.yml
- include: bootstrap_jjb.yml
