---
- name: Create OpenStack instances
  os_server:
    state: present
    cloud: "{{item.os_client_config_cloud | default(os_client_config_cloud) }}"
    name: "{{ item.name }}.{{ domainname }}"
    image: "{{ item.image }}"
    key_name: "{{ key_name }}"
    timeout: 200
    flavor: "{{ item.flavor }}"
    nics:
      - net-name: "{{ item.net_name }}"
    security_groups: "{{ item.security_groups }}"
    auto_floating_ip: yes
    meta:
      group: infra
      infra_type: "{{ item.infra_type }}"
  with_items: infra_servers

- name: Create OpenStack volumes
  os_volume:
    state: present
    cloud: "{{item.os_client_config_cloud | default(os_client_config_cloud) }}"
    display_name: "{{ item.1.name }}"
    size: "{{ item.1.size }}"
  with_subelements:
    - infra_servers
    - volumes
    - { skip_missing: yes }

- name: Attach OpenStack volumes
  os_server_volume:
    state: present
    cloud: "{{item.os_client_config_cloud | default(os_client_config_cloud) }}"
    server: "{{ item.0.name }}.{{ domainname }}"
    volume: "{{ item.1.name }}"
  with_subelements:
    - infra_servers
    - volumes
    - { skip_missing: yes }
