---
- name: Get deb package for Puppetlabs repository
  get_url: >
    url=https://apt.puppetlabs.com/puppetlabs-release-{{ansible_distribution_release}}.deb
    dest=/tmp/puppetlabs-release-{{ansible_distribution_release}}.deb

- name: Install Puppetlabs repository deb package
  apt: deb=/tmp/puppetlabs-release-{{ansible_distribution_release}}.deb

- name: Update packages 
  apt: update_cache=yes

- name: Install Puppet and other required packages
  apt: name={{ item }} state=installed
  with_items:
    - git
    - python-pip
    - puppet
